name: benches

on:
    push:
      branches: ["main"]
    pull_request:
    workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: benchmark
        run: cargo bench --verbose